export const ACTIONS_TODO_TYPES = Object.freeze({
  GETALLTODOS: "GETALL",
  ADDTODO: "ADDTODO",
  UPDATETODO: "UPDATETODO",
  DELETETODO: "DELETETODO",
  SETLOADING: "SETLOADING",
  SETERROR: "SETERROR",
});
